# Generated by Django 3.1.5 on 2022-03-30 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220330_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdevice',
            old_name='User',
            new_name='user',
        ),
    ]
